### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by qing-song** [JakeLin/SwiftWeather#48]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.rc.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9ea777182c3ec95fceda7ee698324f29535b774b
```

### Plugins

```
cocoapods-check           : 0.2.1.beta.1
cocoapods-deintegrate     : 1.0.0.rc.1
cocoapods-plugins         : 1.0.0.rc.1
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0.rc.1
cocoapods-stats           : 1.0.0.rc.1
cocoapods-trunk           : 1.0.0.rc.1
cocoapods-try             : 1.0.0.rc.1
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'SwiftWeather' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7.1'
end

target 'SwiftWeatherTests' do
    pod 'Quick'
    pod 'Nimble'
end
```

### Error

```
NoMethodError - undefined method `include?' for nil:NilClass
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:57:in `block in deintegrate_shell_script_phase'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `select'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `deintegrate_shell_script_phase'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:22:in `block in deintegrate_target'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:21:in `deintegrate_target'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:8:in `block (2 levels) in deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `block in deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:6:in `deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (3 levels) in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/config.rb:39:in `with_changes'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (2 levels) in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `block in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:495:in `deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:132:in `block in prepare'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:131:in `prepare'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:113:in `install!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60include%3F%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by JakeLin** [comment]
Thanks @qing-song sorry for the late action. The issue should be fixed now.
